{% set name = "mdit-py-plugins" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5f2cd1fdb606ddf152d37ec30e46101a60512bc0e5fa1a7002c36647b09e26b5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core >=3.4,<4
    - pip
    - python {{ python_min }}
  run:
    - markdown-it-py >=1.0.0,<4.0.0
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - mdit_py_plugins
    - mdit_py_plugins.amsmath
    - mdit_py_plugins.anchors
    - mdit_py_plugins.container
    - mdit_py_plugins.deflist
    - mdit_py_plugins.dollarmath
    - mdit_py_plugins.footnote
    - mdit_py_plugins.front_matter
    - mdit_py_plugins.myst_blocks
    - mdit_py_plugins.myst_role
    - mdit_py_plugins.tasklists
    - mdit_py_plugins.texmath

about:
  home: https://github.com/executablebooks/mdit-py-plugins
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Collection of plugins for markdown-it-py
  doc_url: https://markdown-it-py.readthedocs.io/en/latest/plugins.html

extra:
  recipe-maintainers:
    - dopplershift
    - choldgraf
    - chrisjsewell
